# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apar',
            name='inspeksi_terakhir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VerificationReport'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='catatan',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Ditolak'), (0, 'Menunggu Verifikasi'), (1, 'Terverifikasi')], default=0),
        ),
    ]
