# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170714_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='catatan',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
