# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170714_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Ditolak'), (1, 'Terverifikasi')], null=True),
        ),
    ]
