# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170714_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationreport',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.InspectionReport'),
        ),
    ]
