# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170717_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesslevel',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Inspector')], default=1),
        ),
    ]
