# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170717_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationreport',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InspectionReport'),
        ),
    ]
