# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=128)),
                ('nomor_lokasi', models.CharField(max_length=8)),
                ('jenis', models.CharField(max_length=8)),
                ('kapasitas', models.IntegerField()),
                ('kondisi', models.IntegerField(choices=[(-1, 'Bad'), (0, 'Unknown'), (1, 'Good')], default=0)),
                ('catatan', models.TextField(max_length=1024)),
                ('pengisian', models.DateField(blank=True, null=True)),
                ('pengecekan', models.DateField(blank=True, null=True)),
                ('qrcode', models.ImageField(upload_to='')),
            ],
        ),
    ]
