# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_apar_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apar',
            name='catatan',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
