# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170706_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apar',
            name='pengisian',
        ),
        migrations.AddField(
            model_name='apar',
            name='kadaluarsa',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='qrcode'),
        ),
    ]
