# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170709_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='apar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Apar'),
        ),
    ]
