# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170710_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='base64',
            field=models.CharField(default='1234324', max_length=1024),
            preserve_default=False,
        ),
    ]
